branches:
    only:
        - master

language: python

python:
    - "2.6"
    - "2.7"

install:
    - python bootstrap.py
    - bin/buildout -c devel.cfg
    - bin/django syncdb --migrate

script: bin/django test
