--- !ditz.rubyforge.org,2008-03-06/project 
name: lakaxita
version: "0.1"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: lakaxita
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: Setup
  status: :released
  release_time: 2012-11-22 23:41:56.589233 Z
  log_events: 
  - - 2012-11-22 23:41:56.589245 Z
    - Unai Zalakain <unai@gisa-elkartea.org>
    - released
    - initial project setup done
- !ditz.rubyforge.org,2008-03-06/release 
  name: Prooves
  status: :released
  release_time: 2012-11-29 08:41:35.304037 Z
  log_events: 
  - - 2012-11-29 08:41:35.304056 Z
    - Unai Zalakain <unai@gisa-elkartea.org>
    - released
    - everything is more or less tied together
- !ditz.rubyforge.org,2008-03-06/release 
  name: Development
  status: :unreleased
  release_time: 
  log_events: []

- !ditz.rubyforge.org,2008-03-06/release 
  name: Applications
  status: :unreleased
  release_time: 
  log_events: []

- !ditz.rubyforge.org,2008-03-06/release 
  name: Fixing
  status: :unreleased
  release_time: 
  log_events: []

- !ditz.rubyforge.org,2008-03-06/release 
  name: Production
  status: :unreleased
  release_time: 
  log_events: []

