--- !ditz.rubyforge.org,2008-03-06/project 
name: lakaxita
version: "0.1"
components: 

- !ditz.rubyforge.org,2008-03-06/component 
  name: lakaxita
releases: 

- !ditz.rubyforge.org,2008-03-06/release 
  name: Setup
  status: :unreleased
  release_time: 

- !ditz.rubyforge.org,2008-03-06/release 
  name: Prooves
  status: :unreleased
  release_time: 

- !ditz.rubyforge.org,2008-03-06/release 
  name: Development
  status: :unreleased
  release_time: 

- !ditz.rubyforge.org,2008-03-06/release 
  name: Applications
  status: :unreleased
  release_time: 

- !ditz.rubyforge.org,2008-03-06/release 
  name: Fixing
  status: :unreleased
  release_time: 

- !ditz.rubyforge.org,2008-03-06/release 
  name: Production
  status: :unreleased
  release_time: 
  log_events: []
